name: langapp
description: A new Flutter project.
publish_to: 'none'
version: 0.1.0

environment:
  sdk: '>=2.19.4 <3.0.0'

dependencies:
  logger: ^2.5.0
  after_layout: ^1.2.0
  # dynamic_color: ^1.6.6
  firebase_auth: ^5.3.4
  firebase_core: ^3.8.1
  flutter:
    sdk: flutter
  shared_preferences: ^2.2.0
  animated_text_kit: ^4.2.2
  cloud_firestore: ^5.5.1
  animate_do: ^3.0.2
  google_nav_bar: ^5.0.6
  flutter_staggered_grid_view: ^0.7.0
  percent_indicator: ^4.2.3
  translator: ^1.0.3+1
  hive: ^2.2.3
  hive_flutter: 
  lottie: ^3.1.3
  text_to_speech: ^0.2.3
  speech_to_text: ^7.0.0
  permission_handler: ^11.3.1
  flutter_tts: ^4.2.0
  flutter_localizations:
    sdk: flutter
  intl: any
  path_provider: ^2.1.0
  syncfusion_flutter_signaturepad: ^27.2.5
  firebase_storage: ^12.3.7
  google_sign_in: ^6.1.4
  image_picker: ^1.0.2
  cool_dropdown: ^2.1.0
  provider: ^6.0.5
  get: ^4.6.5
  line_icons: ^2.0.3
  url_launcher: ^6.1.11
  timeago: ^3.3.0
  http: ^1.2.2
  google_vision: ^1.0.7+7
  flutter_svg: ^2.0.5
  googleapis_auth: ^1.4.1
  image: ^4.3.0


dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0
  hive_generator: 
  build_runner: 


flutter:
  uses-material-design: true
  assets:
    - assets/
    - assets/flag/
  fonts:
    - family: Ubuntu
      fonts:
        - asset: assets/Rubik-Regular.ttf





        # 