// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyB_Hzem_rM0KVeAlHH8uVQ5amxJnzC-00A',
    appId: '1:781162227046:web:5bcedb390e787b1de954a7',
    messagingSenderId: '781162227046',
    projectId: 'language-learning-app-887e6',
    authDomain: 'language-learning-app-887e6.firebaseapp.com',
    storageBucket: 'language-learning-app-887e6.firebasestorage.app',
    measurementId: 'G-36RGDE7FXZ',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCAtCqWfBEFaqGzfy2CrMMrY1S9jHjcpUE',
    appId: '1:781162227046:android:71acd36b79c0a86be954a7',
    messagingSenderId: '781162227046',
    projectId: 'language-learning-app-887e6',
    storageBucket: 'language-learning-app-887e6.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyA3udhf3PM5aZlxlbYTSUoaQWKl9BliHyo',
    appId: '1:781162227046:ios:1bb893bfa44f5fede954a7',
    messagingSenderId: '781162227046',
    projectId: 'language-learning-app-887e6',
    storageBucket: 'language-learning-app-887e6.firebasestorage.app',
    iosBundleId: 'com.example.langapp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyA3udhf3PM5aZlxlbYTSUoaQWKl9BliHyo',
    appId: '1:781162227046:ios:1bb893bfa44f5fede954a7',
    messagingSenderId: '781162227046',
    projectId: 'language-learning-app-887e6',
    storageBucket: 'language-learning-app-887e6.firebasestorage.app',
    iosBundleId: 'com.example.langapp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyB_Hzem_rM0KVeAlHH8uVQ5amxJnzC-00A',
    appId: '1:781162227046:web:92da2ab2055ae9a2e954a7',
    messagingSenderId: '781162227046',
    projectId: 'language-learning-app-887e6',
    authDomain: 'language-learning-app-887e6.firebaseapp.com',
    storageBucket: 'language-learning-app-887e6.firebasestorage.app',
    measurementId: 'G-FFSS4CHZN8',
  );

}